### ISSUE TITLE
[Bug]: Liteeco doesn't activate in 1.19.4

### ISSUE THREAD

**Issue by Nekroz0701** [EncryptSL/LiteEco#55] opened 2023-06-05 17:45 UTC
### What happened?

Error when i launch the plugin in my 1.19.4 server (hosted by aternos).
I tried different version of the plugin but nothing i got the same error.

(I have Spigot on my server not PaperMC)

### Plugin Version

1.3.5-SNAPSHOT

### You detected problem on this server platform ?

PaperMC

### Version /version - output

```shell
.
```

### Relevant log output

```shell
[18:39:03] [Server thread/INFO]: [LiteEco] Enabling LiteEco v1.3.5-SNAPSHOT
[18:39:03] [Server thread/INFO]: [LiteEco] PlaceholderAPI hook initialized
[18:39:04] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: liteeco [1.0.2]
[18:39:04] [Server thread/INFO]: [LiteEco] Registered Vault like a service.
[18:39:04] [Server thread/INFO]: [LiteEco] Treasury not found, for better experience please download Treasury or Vault.
[18:39:04] [Server thread/INFO]: [LiteEco] You are using current version !
[18:39:04] [Server thread/INFO]: [LiteEco] Registering commands with Cloud Command Framework !
[18:39:05] [Server thread/ERROR]: Error occurred while enabling LiteEco v1.3.5-SNAPSHOT (Is it up to date?)
encryptsl.cekuj.net.cloud.bukkit.BukkitCommandManager$BrigadierFailureException: Could not initialize Brigadier mappings. Reason: version too high ()
	at encryptsl.cekuj.net.cloud.bukkit.BukkitCommandManager.registerBrigadier(BukkitCommandManager.java:343) ~[?:?]
	at encryptsl.cekuj.net.cloud.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:125) ~[?:?]
	at encryptsl.cekuj.net.LiteEco.registerCommands(LiteEco.kt:86) ~[?:?]
	at encryptsl.cekuj.net.LiteEco.onEnable(LiteEco.kt:65) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:541) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3762-Spigot-7d7b241-2270366]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:455) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3762-Spigot-7d7b241-2270366]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:220) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3762-Spigot-7d7b241-2270366]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3762-Spigot-7d7b241-2270366]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3762-Spigot-7d7b241-2270366]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by EncryptSL** [comment] 2023-06-05 18:22
Duplicate off #54 , no confirmed....

**Closed by EncryptSL** 2023-06-05 18:22 UTC
Labels: Bug, NotFixed
